# Generated by Django 4.2.6 on 2023-11-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
